/**
 * corporation.ts — Corporation, CorpAssets, and related types.
 *
 * Corporations are autonomous AI-driven entities that perform all economic, scientific,
 * military, and infrastructure activity. The player interacts with them through contracts
 * and investment, never through direct command.
 */

import type {
  CorpId,
  PlanetId,
  ColonyId,
  SchematicId,
  PatentId,
  TurnNumber,
  CorpType,
  CorpPersonalityTrait,
} from './common'
import type { InfraDomain } from './common'

// ─── Corp Assets ──────────────────────────────────────────────────────────────

/**
 * A record of a corporation's owned infrastructure on a specific colony.
 * Keyed by domain; value is the number of levels owned.
 */
export type CorpInfrastructureHoldings = Partial<Record<InfraDomain, number>>

/**
 * All assets a corporation owns across all planets.
 *
 * TODO (Story 11.1): Updated by corp-ai.ts when corps invest in infrastructure.
 * TODO (Story 14.3): Schematics added by schematic-generator.ts.
 */
export interface CorpAssets {
  /**
   * Infrastructure owned per colony.
   * Key: ColonyId, Value: map of domain → levels owned.
   */
  infrastructureByColony: Map<ColonyId, CorpInfrastructureHoldings>
  /** Schematics developed by this corp (shipbuilding corps only). */
  schematics: SchematicId[]
  /** Patents developed by this corp. */
  patents: PatentId[]
}

// ─── Corporation ──────────────────────────────────────────────────────────────

/**
 * An autonomous corporation entity.
 *
 * Corporations are generated via contract kickstart or organic colony emergence.
 * They grow through contract revenue, invest capital autonomously, and can merge
 * or acquire other corporations at level 6+.
 *
 * TODO (Story 11.1): corp-ai.ts implements the corporation AI turn logic.
 * TODO (Story 11.2): corp-phase.ts integrates corp AI into turn resolution.
 */
export interface Corporation {
  id: CorpId
  name: string
  type: CorpType
  /** Current level (1-10). Affects contract quality, investment ability, and megacorp status. */
  level: number
  /**
   * Financial reserves. Used to invest in infrastructure, level up, and acquire corps.
   * Gain: random(0,1) + floor(totalOwnedInfra / 10) per turn + contract completion bonuses.
   */
  capital: number
  /** 1 or 2 personality traits. Influences AI behavior (future implementation). */
  traits: CorpPersonalityTrait[]
  /** The colony where this corporation was founded. */
  homePlanetId: PlanetId
  /** All colonies where this corp currently has infrastructure or operations. */
  planetsPresent: PlanetId[]
  assets: CorpAssets
  /**
   * Tracks the colonies where this corp is currently operating under a contract.
   * Used to determine eligibility for new contracts.
   */
  activeContractIds: string[]
  /** Turn this corporation was founded. */
  foundedTurn: TurnNumber
}

// ─── Capital Action Log ───────────────────────────────────────────────────────

/**
 * A record of a corporation's capital spending action for event/history tracking.
 * TODO (Story 11.1): Generated by corp-ai.ts and returned as events.
 */
export type CapitalActionType =
  | 'invest_infrastructure'
  | 'level_up'
  | 'acquire_corp'
  | 'commission_ship'
  | 'commission_outpost'

export interface CapitalAction {
  type: CapitalActionType
  corpId: CorpId
  capitalSpent: number
  targetId?: string
  turn: TurnNumber
}
