/**
 * event.ts — Game event types.
 *
 * Events are generated by all game systems and displayed in the event feed,
 * priority-sorted. They serve as the game's narrative layer.
 *
 * Event infrastructure is implemented in Epic 19. Threat events are deferred
 * from the prototype (see Specs.md § 13).
 *
 * TODO (Story 19.1): event.store.ts manages event queue and history.
 * TODO (Story 19.2): notification display in the UI.
 */

import type { EventId, TurnNumber, EventPriority } from './common'

// ─── Event Category ───────────────────────────────────────────────────────────

/**
 * Broad category of a game event, used for filtering and icon selection.
 */
export type EventCategory =
  | 'contract'    // Contract completion, progress milestone
  | 'colony'      // Population growth, attribute warning, founding
  | 'corporation' // Corp founded, level up, acquisition
  | 'science'     // Discovery, level advancement
  | 'fleet'       // Ship built, ship lost, mission complete
  | 'budget'      // Debt warning, income change
  | 'exploration' // Planet discovered, sector explored
  | 'threat'      // Future: piracy, unrest, disasters
  | 'system'      // Turn start, autosave, etc.

// ─── Game Event ───────────────────────────────────────────────────────────────

/**
 * A game event generated by any system during turn resolution.
 * Displayed in the event feed, priority-sorted (Critical first).
 *
 * Critical events cannot be dismissed without being viewed.
 * Events link to related entities for navigation in the UI.
 */
export interface GameEvent {
  id: EventId
  turn: TurnNumber
  priority: EventPriority
  category: EventCategory
  title: string
  /** Longer description shown when the event is expanded. */
  description: string
  /** IDs of related game entities (colony, corp, contract, etc.) for navigation. */
  relatedEntityIds: string[]
  /** Whether the player has seen/acknowledged this event. */
  dismissed: boolean
}
