/**
 * game.ts — GameState master type combining all domain states.
 *
 * GameState is the single source of truth passed through the turn resolver.
 * Engine functions receive GameState as input and return updated GameState as output.
 * Pinia stores hold slices of GameState and assemble it via game.store.ts.
 *
 * NOTE: Maps and Sets in GameState must be serialized/deserialized for save files.
 * See utils/save.ts for the serialization strategy.
 *
 * TODO (Story 12.4): game.store.ts assembles GameState from all stores via getFullGameState().
 */

import type { TurnNumber, BPAmount, SectorId } from './common'
import type { Colony } from './colony'
import type { Planet } from './planet'
import type { Corporation } from './corporation'
import type { Contract } from './contract'
import type { Ship } from './ship'
import type { Mission } from './mission'
import type { ScienceDomainState, Discovery, Schematic, Patent } from './science'
import type { SectorMarketState } from './trade'
import type { TradeRoute } from './trade'
import type { Sector } from './sector'
import type { Galaxy } from './sector'
import type { GameEvent } from './event'
import type { BudgetState } from './budget'
import type { EmpireBonuses } from './empire'

// ─── Game Phase ───────────────────────────────────────────────────────────────

/**
 * The current phase of the game loop.
 * - player_action: Player is making decisions (contracts, investments, missions)
 * - resolving: Turn resolution pipeline is running (brief async state)
 * - reviewing: Player is reviewing new turn events before acting
 */
export type GamePhase = 'player_action' | 'resolving' | 'reviewing'

// ─── GameState ────────────────────────────────────────────────────────────────

/**
 * The complete game state. Passed to all turn resolution phases as input.
 * Each phase returns an updated GameState; stores write the result back.
 *
 * All maps use entity ID strings as keys for JSON serializability.
 */
export interface GameState {
  /** Current turn number. Increments at the end of each turn resolution. */
  turn: TurnNumber

  /** Current phase of the game loop. */
  phase: GamePhase

  // ─── Budget ──────────────────────────────────────────────────────────────
  /** Current BP available to the player. */
  currentBP: BPAmount
  /** Current debt token count (0-10). */
  debtTokens: number
  budget: BudgetState

  // ─── Empire-Wide Bonuses ─────────────────────────────────────────────────
  /**
   * Cumulative empire-wide bonuses from science discoveries.
   * Applied uniformly to all ship builds and infrastructure cap calculations.
   * NOT modifiers — simple cumulative state values.
   *
   * TODO (Story 14.2): Incremented when discoveries are applied.
   */
  empireBonuses: EmpireBonuses

  // ─── Galaxy ───────────────────────────────────────────────────────────────
  galaxy: Galaxy

  // ─── Entities (indexed by ID for O(1) lookup) ────────────────────────────
  colonies: Map<string, Colony>
  planets: Map<string, Planet>
  corporations: Map<string, Corporation>
  contracts: Map<string, Contract>
  ships: Map<string, Ship>
  missions: Map<string, Mission>

  // ─── Science ─────────────────────────────────────────────────────────────
  /** Science domain states, keyed by ScienceSectorType string. */
  scienceDomains: Map<string, ScienceDomainState>
  discoveries: Map<string, Discovery>
  schematics: Map<string, Schematic>
  patents: Map<string, Patent>

  // ─── Trade & Market ───────────────────────────────────────────────────────
  /** Per-sector market state from last turn resolution, keyed by SectorId. */
  sectorMarkets: Map<string, SectorMarketState>
  /** Active trade routes between adjacent sectors. */
  tradeRoutes: TradeRoute[]

  // ─── Events ───────────────────────────────────────────────────────────────
  /**
   * All events generated by turn resolution (current turn + recent history).
   * The event store limits history to the last 50 turns.
   */
  events: GameEvent[]

  // ─── Metadata ────────────────────────────────────────────────────────────
  /** ISO timestamp of when this game was started. */
  startedAt: string
  /** ISO timestamp of the last save. */
  lastSavedAt: string
}

// ─── Phase Result ─────────────────────────────────────────────────────────────

/**
 * Standard result type returned by each turn resolution phase.
 * Each phase returns the updated state and any events it generated.
 * Phases are pure functions: no side effects, no store access.
 */
export interface PhaseResult {
  updatedState: GameState
  events: GameEvent[]
}

// ─── Save File ────────────────────────────────────────────────────────────────

/**
 * The persisted save file format. Versioned for future migration compatibility.
 * See utils/save.ts for serialization implementation.
 *
 */
export interface SaveFile {
  version: number
  timestamp: string
  gameState: GameState
}
