/**
 * mission.ts — Mission, TaskForce, and MissionReport types.
 *
 * Missions are the player's military interaction. The player never directly controls
 * ships — they define a mission and a task force executes it.
 *
 * TODO (Story 16.1): create-mission.ts validates and creates Mission objects.
 * TODO (Story 16.3): mission-phase.ts advances missions through phases.
 * TODO (Story 16.4): mission.store.ts manages active/completed missions.
 */

import type {
  MissionId,
  ShipId,
  SectorId,
  CaptainId,
  TurnNumber,
  BPAmount,
  MissionType,
  MissionPhase,
} from './common'

// ─── Task Force ───────────────────────────────────────────────────────────────

/**
 * The assembled fleet for a mission.
 * Ships from multiple corps can combine into a single task force.
 * The highest-experience captain becomes commander.
 */
export interface TaskForce {
  shipIds: ShipId[]
  /** The captain of the ship with the highest experience level. */
  commanderCaptainId: CaptainId
}

// ─── Mission Report ───────────────────────────────────────────────────────────

/**
 * Summary report generated on mission completion.
 * In worst-case scenarios, this may be replaced by "Task Force has not returned."
 *
 * TODO (Story 16.3): Generated by mission-phase.ts on mission completion.
 */
export interface MissionReport {
  missionId: MissionId
  outcome: 'success' | 'partial_success' | 'failure' | 'missing'
  /** Human-readable summary. */
  summary: string
  shipsLost: ShipId[]
  shipsReturned: ShipId[]
  /** Combat rounds summary, if applicable. */
  combatSummary?: string
}

// ─── Mission ──────────────────────────────────────────────────────────────────

/**
 * An active or completed military mission.
 */
export interface Mission {
  id: MissionId
  type: MissionType
  phase: MissionPhase
  targetSectorId: SectorId
  taskForce: TaskForce
  /** BP cost per turn for the duration of this mission. */
  bpPerTurn: BPAmount
  /** Turns remaining for travel to target sector. */
  travelTurnsRemaining: number
  /** Turns remaining for mission execution phase. */
  executionTurnsRemaining: number
  /** Turns remaining for return travel. */
  returnTurnsRemaining: number
  startTurn: TurnNumber
  completedTurn: TurnNumber | null
  /** Report generated on completion. Null while mission is in progress. */
  report: MissionReport | null
}
